apiVersion: v1
kind: Service
metadata:
  name: lamp-service
  labels:
    tier: frontend
    app: lamp
spec:
  type: LoadBalancer
  ports:
   - port: 80
     nodePort: 30008
  selector:
    app: lamp
    