apiVersion: v1
kind: PersistentVolume
metadata:
  name: lamp-pv
spec:
  capacity:
    storage: 750Mi
  accessModes:
      - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data
      