apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-wp
  labels:
    tier: frontend
    app: lamp
spec:
  strategy:
    type: Recreate
  selector: 
    matchLabels:
      app: lamp
      tier: frontend
  template:
    metadata:
      labels: 
        app: lamp
        tier: frontend
    spec:
      containers:
        - name: httpd-php-wp-container
          image: wordpress:php7.4-apache
          volumeMounts:
          - name: lamp-persistent-storage
            mountPath: /var/www/html
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: mysql-root-pass
                key: password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef: 
                name: mysql-db-url
                key: database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef: 
                name: mysql-user-pass
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: mysql-user-pass
                key: password
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef: 
                name: mysql-host
                key: host
        - name: mysql-container
          image: mysql:5.6
          volumeMounts:
          - name: lamp-persistent-storage
            mountPath: /var/www/html 
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: mysql-root-pass
                key: password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef: 
                name: mysql-db-url
                key: database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef: 
                name: mysql-user-pass
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: mysql-user-pass
                key: password
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef: 
                name: mysql-host
                key: host
      volumes:
      - name:  lamp-persistent-storage  
        persistentVolumeClaim:
          claimName: lamp-pv-claim