apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lamp-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 550Mi      