apiVersion: v1
kind: Service
metadata:
  name: nagios-service
  labels:
    app: nagios
spec:
  selector:
    app: nagios
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30008
  type: LoadBalancer
