apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagios-deployment
  labels:
    app: nagios
spec:
  selector:
    matchLabels:
      app: nagios
  template:
    metadata:
      labels:
        app: nagios                                                                                                                                              
    spec:
      containers:
      - name:  nagios-container
        image: jasonrivers/nagios